-- INFO:  Setting up the basic dap-ui using nvim-dap-ui plugin
return {
  "igorfls/nvim-dap-view",
  -- "rcarriga/nvim-dap-ui",
  -- dependencies = {
  --   "mfussenegger/nvim-dap",
  --   "nvim-neotest/nvim-nio",
  --   "theHamsta/nvim-dap-virtual-text",
  -- },
  -- keys = {
  --   {
  --     "<leader>du",
  --     function()
  --       require("dapui").toggle({})
  --     end,
  --     desc = "Toggle DAPUI",
  --   },
  --
  --   {
  --     "<leader>de",
  --     function()
  --       require("dapui")
  --     end,
  --     desc = "Eval",
  --     mode = { "n", "v" },
  --   },
  -- },
  -- opts = {
  --   icons = {
  --     expanded = "▾",
  --     collapsed = "▸",
  --     current_frame = "➜",
  --   },
  --   mappings = {
  --     expand = { "<CR>", "<2-LeftMouse>" },
  --     open = "o",
  --     remove = "d",
  --     edit = "e",
  --     repl = "r",
  --     toggle = "t",
  --   },
  --   element_mappings = {},
  --   expand_lines = true,
  --   force_buffers = true,
  --   wrap = true,
  --   floating = {
  --     max_height = nil,
  --     max_width = nil,
  --     border = "rounded",
  --     mappings = {
  --       close = { "q", "<Esc>" },
  --     },
  --   },
  --   controls = {
  --     enabled = true,
  --     element = "repl",
  --     icons = {
  --       pause = "",
  --       play = "",
  --       step_into = "",
  --       step_over = "",
  --       step_out = "",
  --       step_back = "",
  --       run_last = "↻",
  --       terminate = "□",
  --       disconnect = "⏏",
  --     },
  --   },
  --   layouts = {
  --     {
  --       elements = {
  --         { id = "scopes", size = 0.40 },
  --         { id = "breakpoints", size = 0.15 },
  --         { id = "stacks", size = 0.25 },
  --         { id = "watches", size = 0.20 },
  --       },
  --       size = 42,
  --       position = "left",
  --     },
  --     {
  --       elements = {
  --         { id = "repl", size = 0.50 },
  --         { id = "console", size = 0.50 },
  --       },
  --       size = 12,
  --       position = "bottom",
  --     },
  --   },
  --   render = {
  --     indent = 1,
  --     max_value_lines = 100,
  --   },
  -- },
  -- --  INFO: Calling config for nvim-dap-ui and passing in the opts to be merged
  -- config = function(_, opts)
  --   local dap = require("dap")
  --   local dapui = require("dapui")
  --
  --   -- INFO: Setting up dap-ui with the ability to use virtual text
  --   require("nvim-dap-virtual-text").setup({
  --     enabled = true,
  --     enable_commands = true,
  --     highlight_changed_variables = true,
  --     highlight_new_as_changed = false,
  --     show_stop_reason = true,
  --     commented = false,
  --     only_first_definition = true,
  --     all_references = false,
  --     clear_on_continue = false,
  --   })
  --
  --   dapui.setup(opts)
  --
  --   dap.listeners.before.attach.dapui_config = function()
  --     dapui.open({})
  --   end
  --
  --   dap.listenere.before.launch.dapui_config = function()
  --     dapui.open({})
  --   end
  --
  --   dap.listeners.before.event_terminated.dapui_config = function()
  --     dapui.close({})
  --   end
  --   dap.listeners.before.event_exited.dapui_config = function()
  --     dapui.close({})
  --   end
  -- end,
}
