return {

  -- add any tools you want to have installed below
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "angular-language-server",
        "ansible-language-server",
        "ansible-lint",
        "astro-language-server",
        "bash-language-server",
        "debugpy",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "eslint_d",
        "flake8",
        "google-java-format",
        "hadolint",
        "java-debug-adapter",
        "java-test",
        "jdtls",
        "js-debug-adapter",
        "json-lsp",
        "lemminx",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "php-cs-fixer",
        "php-debug-adapter",
        "phpactor",
        "phpcs",
        "prettier",
        "prettierd",
        "prisma-language-server",
        "pyright",
        "ruff",
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "stylua",
        "tailwindcss-language-server",
        "taplo",
        "vscode-spring-boot-tools",
        "vtsls",
        "vue-language-server",
        "xmlformatter",
        "yaml-language-server",
      },
    },
  },

  -- since `vim.tbl_deep_extend`, can only merge tables and not lists, the code above
  -- would overwrite `ensure_installed` with the new value.
  -- If you'd rather extend the default config, use the code below instead:
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      -- add tsx and treesitter
      vim.list_extend(opts.ensure_installed, {
        "tsx",
        "typescript",
        "angular",
        "astro",
        "bash",
        "c",
        "css",
        "diff",
        "dockerfile",
        "dtd",
        "ecma",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "graphql",
        "html",
        "html_tags",
        "http",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "jsx",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "ninja",
        "php",
        "php_only",
        "printf",
        "prisma",
        "python",
        "query",
        "regex",
        "rst",
        "scss",
        "sql",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
      })
    end,
  },

  -- add gruvbox
  { "ellisonleao/gruvbox.nvim" },
  {
    "eldritch-theme/eldritch.nvim",
    lazy = false,
    priority = 1000,
    opts = {},
  },
  {
    "craftzdog/solarized-osaka.nvim",
    lazy = false,
    priority = 1000,
    opts = {},
  },
  {
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
  },

  -- Configure LazyVim to load colorscheme of choice
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = { "cyberdream" },
    },
  },
}
