#!/bin/bash
# Generated by chezmoi on {{ now | date "2006-01-02 15:04:05" }}

# Colors for output
if [ -n "${LOGGING_SH_SOURCED:-}" ]; then
  return 0
fi
readonly LOGGING_SH_SOURCED=1

#INFO: Colors for output - only declare if not already set
if [ -z "${RED:-}" ]; then
  readonly RED='\033[0;31m'
fi

if [ -z "${GREEN:-}" ]; then
  readonly GREEN='\033[0;32m'
fi
if [ -z "${YELLOW:-}" ]; then
  readonly YELLOW='\033[1;33m'
fi
if [ -z "${BLUE:-}" ]; then
  readonly BLUE='\033[0;34m'
fi
if [ -z "${NC:-}" ]; then
  readonly NC='\033[0m' # No Color
fi

# Logging functions
log_info() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
  echo -e "${BLUE}[STEP]${NC} $1"
}
